= Gloo Edge/Envoy External Authorization to Validate SOAP Messages

This project provides a reference implementation for a custom external authorization service that can be used with Gloo Edge to validate SOAP/XML messages that use the WS-Security SOAP extensions. The implementation is narrow focus, and may need to be modified for your specific configurations for SOAP and associated WS-Security.

You might consider using this implementation if you are looking to replace a legacy middeware (and applicances), such as DataPower, to validate SOAP messages before they are forwarded to backend SOAP endpoints. Just the same as DataPower, Gloo Edge can then be a "firewall" to deny invalid SOAP messages before they get inside your internal network. You can also combine this authorization mechanism with other Gloo Edge features, such as rate limiting, to have a comprehensive solution for a safe and performant SOAP gateway into your system.

== Technologies Used

* Gloo Edge (which also uses Envoy)
* Kubernetes to deploy Gloo Edge
* Docker to build an image
* Java 11, including numerous built-in APIs for security and XML
* gRPC, including pre-generated Java code to build a gRPC Service for Envoy
* Vert.x to launch the gRPC service
* Vault to generate certificates for testing purposes



== Setting up a Certificate Authority and Issuing Certificates Using Vault

In order to test this service, you must have a valid Root Certificate Authority (CA) and Intermediate CA. That way you can install the CAs into you this service's JVM TrustStore and also generate public certificates that can be used to generate signed SOAP messages.

The CAs can be easily created using HashiCorp Vault as shown in this https://learn.hashicorp.com/tutorials/vault/pki-engine[article]. Let's walk through the steps required to do this.

=== 1) Install Vault

Follow the instructions https://learn.hashicorp.com/tutorials/vault/getting-started-install?in=vault/getting-started[here] for your operating system.

==== Start Vault in Dev Mode

```
vault server -dev -dev-root-token-id=root
```



=== 2) Install Vault





To make this easier to test, we can use HashiCorp Vault to create a Certificate Authority and generate certificates that can be used
to test the validation of SOAP messages. An article documenting this approach is here



image:https://img.shields.io/badge/vert.x-4.0.0-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```



vault server -dev -dev-root-token-id=root
export VAULT_ADDR='http://127.0.0.1:8200'

=== 1) Generate Root Certificate Authority

vault secrets enable -path=acme_com pki
vault secrets tune -max-lease-ttl=87600h acme_com
vault write -field=certificate acme_com/root/generate/internal common_name="acme.com Root Authority" ttl=87600h > acme_com_ca_cert.crt
vault write acme_com/config/urls issuing_certificates="http://127.0.0.1:8200/v1/acme_com/ca" crl_distribution_points="http://127.0.0.1:8200/v1/acme_com/crl"

=== 2) Generate Intermediate Certificate Authority

```
vault secrets enable -path=service1_acme_com pki
vault secrets tune -max-lease-ttl=26280h service1_acme_com
vault write -format=json service1_acme_com/intermediate/generate/internal common_name="service1.acme.com Intermediate Authority" | jq -r '.data.csr' > service1_acme_com_ca_cert.csr
vault write -format=json acme_com/root/sign-intermediate csr=@service1_acme_com_ca_cert.csr format=pem_bundle ttl="26280h" | jq -r '.data.certificate' > service1_acme_com_ca_cert.crt
vault write service1_acme_com/intermediate/set-signed certificate=@service1_acme_com_ca_cert.crt
```

=== 3) Issue Client Keys and Certificates

==== a) Create a Role

```
vault write service1_acme_com/roles/partner_com allowed_domains="partner.com" allow_subdomains=true max_ttl="13140h"
```

==== b) Issue a Client Private Key and Certificate

```
vault write -format=json service1_acme_com/issue/partner_com common_name="client1.partner.com" ttl="13140h" > client1_partner_com.json
cat client1_partner_com.json | jq -r '.data.private_key' > client1_partner_com.pem
cat client1_partner_com.json | jq -r '.data.certificate' > client1_partner_com.crt
cat client1_partner_com.json | jq -r '.data.issuing_ca' > client1_partner_com_chain.crt
cat client1_partner_com.json | jq -r '.data.ca_chain[]' >> client1_partner_com_chain.crt
rm client1_partner_com.json
```

==== c) Create a PKSC12 Archive File for Distribution to Clients

```
openssl pkcs12 -export -inkey client1_partner_com.pem -in client1_partner_com.crt -certfile client1_partner_com_chain.crt -name client1_partner_com -out client1_partner_com.p12
```

Enter a password, such as "password"

=== 4) (Optional) Issue a Service Leaf Certificate for the Service

If you want to provide TLS termination, or potentially mTLS between the client and server, you will need a leaf certificate for the service. This leaf certificate is not needed for the core of this demo, but this demo can be extended to use it.

=== a) Create a Role

```
vault write service1_acme_com/roles/service1_acme_com allowed_domains="service1.acme.com" allow_bare_domains=true allow_subdomains=true max_ttl="8760h"
```

==== b) Issue a Service Private Key and Leaf Certificate

```
vault write -format=json service1_acme_com/issue/service1_acme_com common_name="service1.acme.com" ttl="8760h" > service1_acme_com.json
cat service1_acme_com.json | jq -r '.data.private_key' > service1_acme_com.pem
cat service1_acme_com.json | jq -r '.data.certificate' > service1_acme_com.crt
cat service1_acme_com.json | jq -r '.data.issuing_ca' > service1_acme_com_chain.crt
cat service1_acme_com.json | jq -r '.data.ca_chain[]' >> service1_acme_com_chain.crt
rm service1_acme_com.json
```

=== 5) Install CA Certs into JKS Truststore

keytool -import -alias acme_com_ca_cert -trustcacerts -file acme_com_ca_cert.crt -keystore acme-truststore.jks
keytool -import -alias service1_acme_com_ca_cert -trustcacerts -file service1_acme_com_ca_cert.crt -keystore acme-truststore.jks

System.setProperty("javax.net.ssl.trustStore", "acme-truststore.jks");
-Djavax.net.ssl.keyStore=path/to/acme-truststore.jks

cp acme-truststore.jks ../src/main/resources
cp client1_partner_com.p12 ../src/test/resources

=== 6) Install Cert in JKS Keystore

keytool -importkeystore -srckeystore client1_partner_com.p12 -srcstoretype PKCS12 -storepass changeit -destkeystore partner-keystore.jks

./mvnw compile test -Djavax.net.ssl.trustStore=/home/eric/GitHub/gloo-envoy-ext-auth-xml-sig/certs/acme-truststore.jks -Djavax.net.ssl.trustStorePassword=changeit


./mvnw package

docker build -t murphye/gloo-edge-soap-authorization-service:0.0.8-SNAPSHOT .

docker push murphye/gloo-edge-soap-authorization-service:0.0.8-SNAPSHOT


=== Deploy Custom Auth Service

```
cd demo
kubectl apply -n gloo-system -f deployment.yaml
```



curl -i -w "\n%{time_total}" --header "Content-Type: text/xml" --data-binary @output.soap.xml http://localhost:8081/address-xml
